#pragma config(Sensor, S1,     colorA,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     i2c,            sensorEV3_GenericI2C)
#pragma config(Sensor, S3,     infraR,         sensorEV3_IRSensor)
#pragma config(Sensor, S4,     colorB,         sensorEV3_Color, modeEV3Color_Color)
//S1 = Direita S4 = Esquerda
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Definindo endereços do Arduino
#define ARDUINO_ADDRESS 0x08
#define ARDUINO_PORT S2
#define KP 1
#define KI 0.0
#define KD 0.2
#define SET_POINT 65
#define OFFSET -22
#define TURN_RATE_90 70
#define TURN_TIME_90 60
#define TURN_SPEED_90 30
#define G_THRESH 2.6
#define TURN_ERRO_K 4
#define IMAGE_KP 0.2
#define IMAGE_SETPOINT 47
#define COLOR_ERRO 6

bool resgate = false;
int limiarWhite[2][6];

/* ---------------------------------
||						UTILS								||
--------------------------------- */
// Realiza mudança na magnitude
long map( long x, long in_min, long in_max, long out_min, long out_max){
	return (x - in_min) * ( out_max - out_min) / ( in_max - in_min ) + out_min ;
}
// Pega o maior de três números
int max(int a, int b, int c){
     int m = a;
     (m < b) && (m = b);
     (m < c) && (m = c);
     return m;
}
// Pega o menor de três números
int min(int a, int b, int c){
     int m = a;
     (m > b) && (m = b);
     (m > c) && (m = c);
     return m;
}

/* ---------------------------------
||							I2C								||
--------------------------------- */
// Variável que armazena a posição do sensor de 0 a 127
int linha;
// Variável que armazena o estado especial do sensor de linha
int estado;
// Armazena o status do sensor
TI2CStatus mI2CStatus;
// Armazena a resposta
byte replyMsg[10];
// Armazena a mensagem a ser enviada
byte sendMsg[10];

// Mandar e receber mensagens para o I2C
void i2c_msg(int reply_size, int message_size, byte byte1, byte byte2, byte byte3, byte byte4){
	// Pegando o status do sensor I2C
	mI2CStatus = nI2CStatus[i2c];
	// Reservando espaço na memória para a resposta
	memset(replyMsg, 0, sizeof(replyMsg));
	// Reservando espaço no tamanho da mensagem
	message_size += 3;
	// Atribuindo o tamanho da mensagem e o endereço
	sendMsg[0] = message_size;
	sendMsg[1] = ARDUINO_ADDRESS;
	// Atribuindo os bytes da mensagem
	sendMsg[2] = byte1;
	sendMsg[3] = byte2;
	sendMsg[4] = byte3;
	sendMsg[5] = byte4;

	// Enviando mensagem
	sendI2CMsg(i2c, &sendMsg[0], 2);
	// Esperar 30ms
	wait1Msec(30);

	// Ler resposta
	readI2CReply(i2c, &replyMsg[0], reply_size);

	// Resposta
	linha = replyMsg[0];
	estado = replyMsg[1];
	wait1Msec(35);
}


/* ---------------------------------
||						MOVIMENTOS					||
--------------------------------- */
// Faz o robô andar para frente
void walk(int value, float duration){
	resetMotorEncoder(motorA);
	int a = getMotorEncoder(motorA);
	if(value > 0){

		while(getMotorEncoder(motorA) + duration > a){
			motor[motorA] = -value;
			motor[motorB] = -value;
		}
	}else{
		while(getMotorEncoder(motorA) - duration < a){
			motor[motorA] = -value;
			motor[motorB] = -value;
		}
	}
}
// Faz o robô girar em graus
void turn(float value, bool direction){
	value = map(value, 0, 180, 0, 1320);
	int a = getMotorEncoder(motorA);
	if(direction){
		while(getMotorEncoder(motorA) < a + value){
			motor[motorA] = 30;
			motor[motorB] = -30;
		}
		}	else{
		while(getMotorEncoder(motorA) + value > a ){
			motor[motorA] = -30;
			motor[motorB] = 30;
		}
	}
}

// Lê os valores e estado do QTR8-A
int read_line_sensor(){
	i2c_msg(2,1,1,0,0,0);
	int value = linha;
	return value;
}


// Calibra o threshold de branco e preto
void calibrateThresh(){
	// Calibração do branco
	while(!getButtonPress(buttonEnter)){
		// Pegando cores do sensor esquerdo
		long coresB[3];
		getColorRGB(colorB, coresB[0], coresB[1], coresB[2]);
		// Pegando cores do sensor direito
		long coresA[3];
		getColorRGB(colorA, coresA[0], coresA[1], coresA[2]);

		displayTextLine(1, "CALIBRANDO O BRANCO");
		displayTextLine(4, "E => (R:%d, G:%d, B:%d)", coresB[0], coresB[1], coresB[2]);
		displayTextLine(7, "D => (R:%d, G:%d, B:%d)", coresA[0], coresA[1], coresA[2]);

		for(int a = 0; a < 2; a++){
			for(int b = 0; b < 3; b++){
				limiarWhite[a][b] = (a == 0 ? coresA[b] - COLOR_ERRO : coresB[b] - COLOR_ERRO);
			}
		}
	}
}

// Lê o valor dos sensores de cor
int read_color_sensor(){
	// Pegando cores do sensor esquerdo
	long coresB[3];
	getColorRGB(colorB, coresB[0], coresB[1], coresB[2]);
	// Pegando cores do sensor direito
	long coresA[3];
	getColorRGB(colorA, coresA[0], coresA[1], coresA[2]);
	// Escreve os valores na tela
	displayCenteredBigTextLine(1,"Vermelho: %d %d", coresA[0], coresB[0]);
	displayCenteredBigTextLine(4,"Verde: %d %d", coresA[1], coresB[1]);
	displayCenteredBigTextLine(7,"Azul: %d %d", coresA[2], coresB[2]);
	for(int a = 0; a < 3; a++){
		coresA[a] = map(coresA[a], 0, 90, 0, 255);
	}
	for(int a = 0; a < 3; a++){
		coresB[a] = map(coresB[a], 0, 90, 0, 255);
	}
	// Detecta se o valor do verde passa de certo limiar
	// Esquerda
	if ((coresA[1] >= 40) && ((sqrt(pow(coresA[0], 2) + pow(coresA[2], 2)) - (coresA[1] - 20)) <= 0)){
			displayCenteredBigTextLine(10,"GREEN TURN ESQUERDO");
			return 2;
	}
	// Direita
	if ((coresB[1] >= 40) && ((sqrt(pow(coresB[0], 2) + pow(coresB[2], 2)) - (coresB[1] - 20)) <= 0)){
			displayCenteredBigTextLine(10,"GREEN TURN DIREITO");
			return 1;
	}
	//Cinza

	return 0;
}


/* ---------------------------------
||						   PID    					||
--------------------------------- */
int PID(int input, int offset, int KP1, int SET_POINT1){
	// Ultimo input
	static int lstinput;
	// Erro acumulado
	static float erroAc;
	int erro = input - SET_POINT1;
	float valor = (erro * KP1) + (input - lstinput) * KD + (erroAc) * KI;
	motor[motorA] = valor + offset;
	motor[motorB] = -valor + offset;
	lstinput = input;
	erroAc += erro;
	return erro;
}
// CINZA
bool CinzaT(){

}
// GAP
void GAP(){
	read_line_sensor();
	while(estado == 3){

		motor[motorA] = -20;
		motor[motorB] = -20;
		read_line_sensor();
		displayBigTextLine(10, "%d", estado);
	}
}

// Corrigir
void corrigir(int limiar){
	int erro = read_line_sensor() - SET_POINT;
	while(erro > limiar){
		erro = PID(read_line_sensor(), 0, KP, SET_POINT);
	}
}

// Virada Genérica por erro
void gTurn(bool direction){
	int erro = read_line_sensor() - SET_POINT;
	while((erro > TURN_ERRO_K) || (erro < -TURN_ERRO_K)){
		displayBigTextLine(10, "Erro: %d", erro);
		if(direction){
			motor[motorA] = -30;
			motor[motorB] = 30;
		} else {
			motor[motorA] = 30;
			motor[motorB] = -30;
		}
		erro = read_line_sensor() - SET_POINT;
	}

}

//Virada do Verde
void greenTurn(bool side){
	walk(TURN_SPEED_90, TURN_TIME_90);
	turn(60, side);
	walk(TURN_SPEED_90, TURN_TIME_90/2);
}

//Saída do Verde
void gExit(){
	int cor;
	do{
		cor = read_color_sensor();
		motor[motorA] = -20;
		motor[motorB] = -20;
	}while(cor != 0);
}
/**
* EURÍSTICA
*/
int euState(int cor){
	if(estado == 1){
		displayBigTextLine(10, "90 ESQUERDA %d", estado);
		// 90° ESQUERDA
		// Checando por encruzilhadas
		do{
			read_line_sensor();
			motor[motorA] = -20;
			motor[motorB] = -20;
			int cor = read_color_sensor();

			// Detectando cor
			if(cor == 1){
				greenTurn(false);
				gExit();
				return 0;
			}else if(cor == 2){
				greenTurn(true);
				gExit();
				return 0;
			}
		}while(estado == 1);
		int erro = read_line_sensor() - SET_POINT;
		if(estado == 4){
			//Caso seja uma encruzilhada ou um falso alerta, ajusta até estar na linha perfeitamente
			int erro = read_line_sensor() - SET_POINT;
			if((erro > 20) || (erro < -20)){
				turn(30, false);
			}
			return 0;

		}
		// Checando se é uma curva de 90° ou mais
		else if(estado == 3){
			do{
				read_line_sensor();
				motor[motorA] = 20;
				motor[motorB] = 20;
				int cor = read_color_sensor();

				// Detectando cor
				if(cor == 1){
					greenTurn(false);
					gExit();
					return 0;
				}else if(cor == 2){
					greenTurn(true);
					gExit();
					return 0;
				}
			}while(estado != 3);
			//Vira 90° à esquerda
			gTurn(true);
			//Anda para frente
			do{
				read_line_sensor();
				motor[motorA] = -20;
				motor[motorB] = -20;
				int cor = read_color_sensor();

				// Detectando cor
				if(cor == 1){
					greenTurn(false);
					gExit();
					return 0;
				}else if(cor == 2){
					greenTurn(true);
					gExit();
					return 0;
				}
			}while(estado != 4);
			corrigir(8);
			return 0;
		}
	}
	else if(estado == 2){
		displayBigTextLine(10, "90 DIREITA %d", estado);
		// 90° DIREITA
		// Ler estado atual
		int sensor = read_line_sensor();
		// Checando por encruzilhadas
		do{
			int cor = read_color_sensor();

			// Detectando cor
			if(cor == 1){
				greenTurn(false);
				gExit();
				return 0;
			}else if(cor == 2){
				greenTurn(true);
				gExit();
				return 0;
			}
			read_line_sensor();
			motor[motorA] = -20;
			motor[motorB] = -20;
		}while(estado == 2);
		int erro = read_line_sensor() - SET_POINT;
		if(estado == 4){
			if((erro > 20) || (erro < -20)){
				turn(30, true);
			}
			return 0;
		}
		// Checando se é uma curva de 90° ou mais
		else if(estado == 3){
			do{
				read_line_sensor();
				motor[motorA] = 20;
				motor[motorB] = 20;
				int cor = read_color_sensor();

				// Detectando cor
				if(cor == 1){
					greenTurn(false);
					gExit();
					return 0;
				}else if(cor == 2){
					greenTurn(true);
					gExit();
					return 0;
				}
			}while(estado != 3);
			//Vira 90° à direita
			gTurn(false);
			//vai para trás até encontrar a virada
			do{
				read_line_sensor();
				motor[motorA] = -20;
				motor[motorB] = -20;
				int cor = read_color_sensor();

				// Detectando cor
				if(cor == 1){
					greenTurn(false);
					gExit();
					return 0;
				}else if(cor == 2){
					greenTurn(true);
					gExit();
					return 0;
				}
			}while(estado != 4);
			corrigir(8);
			return 0;
		}
	}
	else if(estado == 3){
		GAP();
	}
	return 0;
}
/**
* LINE FOLLOWING
*/
void lineFollowing(){
	while(1){
		if(getIRDistance(infraR)<20){
			greenTurn(false);
			walk(TURN_SPEED_90, TURN_TIME_90*4);
			greenTurn(true);
			walk(TURN_SPEED_90, TURN_TIME_90*12);
			greenTurn(true);
			read_line_sensor();
			while(estado == 3){

				motor[motorA] = -30;
				motor[motorB] = -30;
				read_line_sensor();
			}
			greenTurn(false);
			walk(-TURN_SPEED_90, TURN_TIME_90*4);
		}
		int sensor = read_line_sensor();
		int cor = read_color_sensor();

		// Detectando cor
		if(cor == 1){
			greenTurn(false);
			gExit();
		}else if(cor == 2){
			greenTurn(true);
			gExit();
		}

		if((sensor <= 127) && (sensor >= 0) && (estado == 4)){
			PID(sensor, OFFSET, KP, SET_POINT);
			displayBigTextLine(10, "%d", estado);
			continue;
		}
		else{
			euState(cor);
		}
	}
}

/**
* RESGASTE
*/
void resgateMode(){
	while(1){
			linha = read_line_sensor();
			//PID(linha, 0, IMAGE_KP, IMAGE_SETPOINT);
			if(linha == 0){
				motor[motorA] = 5;
				motor[motorB] = -5;
			}else{
				if ((linha <= 100 + 5) && (linha >= 100 - 5)){
					walk(10, 1);
				}else if (linha > 100){
					motor[motorA] = 5;
					motor[motorB] = -5;
				}else{
					motor[motorA] = -5;
					motor[motorB] = 5;
				}
			}
			wait1Msec(300);
	}
}

/* ---------------------------------
||						  MAIN	    				||
--------------------------------- */
task main()
{

	calibrateThresh();
	while(1){
		if(!resgate){
			eraseDisplay();
			lineFollowing();
		}
		else
			resgateMode();
		}
}
